---
- name: Log in as root and set up enviorment
  hosts: aws_ec2 # Replace with the appropriate group or hostname
  gather_facts: no # Disable gathering facts, as we're logging in as root
  become: yes # Enable privilege escalation
  vars_files:
    - project-vars
  tasks:
    - name: Execute a command as root
      command: whoami # Replace with the command you want to run
      register: result

    - name: Display the command output
      debug:
        var: result.stdout

    - name: update Yum repo and cache
      yum: update_cache=yes
    - name: Install jdk8 and net-tools
      yum:
        name:
          - java-1.8.0-amazon-corretto
          - net-tools
        state: present

- name: Deploy nodejs app
  hosts: aws_ec2
  gather_facts: no
  become: yes
  vars_files:
    - project-vars

  tasks:
    - name: Check nexus folder stats
      stat:
        path: /opt/nexus
      register: stat_result
    - debug: msg={{stat_result.stat.exists}}

    - name: Download and unpack Nexus installer
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
      when: not stat_result.stat.exists

    - name: print out nexus download file name
      debug: msg={{download_result.dest}}
      when: not stat_result.stat.exists

    - name: untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists

    - name: Find nexus folder
      find:
        paths: /opt/
        pattern: "nexus-*"
        file_type: directory
      register: find_result
      when: not stat_result.stat.exists

    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat

- name: Create nexus user to own nexus folders
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Ensure group nexus exists
      group:
        name: nexus
        state: present
    - name: Create nexus user
      user:
        name: nexus
        group: nexus
    - name: Change ownership of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Change ownership of sonatype folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start nexus with nexus user
  hosts: aws_ec2
  become: yes
  become_user: nexus
  tasks:
    - name: Create nexus.rc file and set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        line: run_as_user="nexus"
        create: yes

    - name: Run nexus
      command: /opt/nexus/bin/nexus start

- name: Verify nexus running
  hosts: aws_ec2
  tasks:
    - name: Pause for 20 seconds
      pause:
        seconds: 20

    - name: Check with ps
      shell: ps ef | grep nexus
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
    - name: Check with netstat
      shell: netstat -lpnt | grep nexus
      register: network_status
    - debug: msg={{network_status.stdout_lines}}
